import json
from fastapi import APIRouter, Request
from dotenv import load_dotenv
from src.context.context_builder import ContextBuilder
from src.orchestration.orchestrator import Orchestrator
from src.github.github_client import GitHubClient

load_dotenv()

router = APIRouter()


@router.post("/webhook/github")
async def github_webhook(request: Request):
    payload = await request.json()
    event_type = request.headers.get("X-GitHub-Event", "unknown")

    print(f"\n=== GITHUB WEBHOOK: {event_type} ===")

    # Ambil repo info dari payload
    owner = payload["repository"]["owner"]["login"]
    repo = payload["repository"]["name"]

    changed_files = extract_changed_files(event_type, payload)

    print(f"Changed files ({len(changed_files)}):")
    for f in changed_files:
        print(f"  - {f}")

    if not changed_files:
        return {"status": "skipped", "reason": "no changed files"}

    ref = payload.get("after") or payload.get("pull_request", {}).get("head", {}).get("sha")
    branch = extract_branch(event_type, payload)

    # Context Builder
    cb = ContextBuilder(owner, repo, ref)
    context = cb.build(changed_files)

    if not context["changed_files"]:
        return {"status": "skipped", "reason": "no analyzable files"}

    # Orchestration → LLM
    orchestrator = Orchestrator()
    result = orchestrator.review_code(context)

    print("\n=== LLM REVIEW RESULT ===")
    print(result)

    # Output → post ke GitHub
    github = GitHubClient(owner, repo)
    pr_number = github.get_open_pr_for_branch(branch) if branch else None

    if pr_number:
        # Ada PR → post sebagai PR comment
        body = format_pr_comment(result)
        github.post_pr_comment(pr_number, body)
        return {"status": "reviewed", "output": "pr_comment", "pr": pr_number}
    else:
        # Tidak ada PR → buat GitHub Issue
        title = f"🤖 CodeGuard AI Review — {branch or ref[:7]}"
        body = format_pr_comment(result)
        github.create_issue(title, body)
        return {"status": "reviewed", "output": "issue"}


def extract_changed_files(event_type: str, payload: dict) -> list[str]:
    files = set()

    if event_type == "push":
        commits = payload.get("commits", [])
        for commit in commits:
            files.update(commit.get("added", []))
            files.update(commit.get("modified", []))

    elif event_type == "pull_request":
        action = payload.get("action")
        pr_number = payload.get("number")
        print(f"PR #{pr_number} action: {action}")
        # PR files diambil via GitHub API di ContextBuilder nanti
        # Untuk sekarang ambil dari head commit
        files_url = payload.get("pull_request", {}).get("url")
        if files_url:
            print(f"[webhook] PR URL: {files_url}")

    return list(files)


def extract_branch(event_type: str, payload: dict) -> str | None:
    if event_type == "push":
        ref = payload.get("ref", "")
        # ref format: "refs/heads/develop"
        return ref.replace("refs/heads/", "") if ref else None
    elif event_type == "pull_request":
        return payload.get("pull_request", {}).get("head", {}).get("ref")
    return None


def format_pr_comment(review_result: str) -> str:
    return f"""## 🤖 CodeGuard AI Review

{review_result}

---
*Generated by [CodeGuard AI](https://github.com/ariefeko/codeguard-ai)*"""


@router.post("/webhook/sentry")
async def sentry_webhook(request: Request):
    payload = await request.json()
    print("\n=== SENTRY WEBHOOK RECEIVED ===")
    print(json.dumps(payload, indent=2, ensure_ascii=False))
    return {"status": "received"}
