from src.config import CODEGUARD_REPOSITORY_URL


def format_pr_comment(review_result: str) -> str:
    return f"""## 🤖 CodeGuard AI Review

{review_result}

---
*Generated by [CodeGuard AI]({CODEGUARD_REPOSITORY_URL})*"""


def format_bug_issue(analysis, error: dict) -> str:
    """
    Format a validated BugAnalysis from schemas.py as a GitHub issue body.
    """
    lines = [
        "## 🤖 CodeGuard AI — Bug Analysis",
        "",
        f"**Error type**: `{error.get('type', 'Unknown')}`",
        f"**Message**: {error.get('message', '')}",
        "",
        "### Root Cause",
        analysis.root_cause,
        "",
        "### Affected File",
        f"`{analysis.affected_file}`" + (f" (line {analysis.affected_line})" if analysis.affected_line else ""),
        "",
        "### Fix Steps",
        analysis.fix_steps,
        "",
        "### Quick Fix",
        f"```\n{analysis.quick_fix_code}\n```",
        "",
        "### Prevention",
        analysis.prevention,
    ]

    if analysis.inferences:
        lines.append("")
        lines.append("### Inferences")
        for inf in analysis.inferences:
            lines.append(f"- **{inf.claim}** _(confidence: {inf.confidence})_ — {inf.basis}")

    if analysis.status == "PARTIAL":
        lines.append("")
        lines.append("_⚠️ The AI classified this analysis as PARTIAL; some information may be missing._")

    lines.append("")
    lines.append("---")
    lines.append(f"*Generated by [CodeGuard AI]({CODEGUARD_REPOSITORY_URL})*")

    return "\n".join(lines)


def format_bug_fallback_issue(error: dict) -> str:
    """
    Build a minimal issue body when fix_bug() returns None because every
    provider failed. The worker uses this as a fallback without AI analysis.
    """
    return f"""## 🤖 CodeGuard AI — Bug Detected (analysis unavailable)

**AI analysis failed for this error** — every provider failed to return a valid response. Raw Sentry error data follows:

- **Type**: {error.get('type', 'Unknown')}
- **Message**: {error.get('message', '')}
- **File**: {error.get('file', '')}
- **Line**: {error.get('line', '')}

Manual review is required.

---
*Generated by [CodeGuard AI]({CODEGUARD_REPOSITORY_URL})*"""
