from src.config import CODEGUARD_REPOSITORY_URL


def format_pr_comment(review_result: str) -> str:
    return f"""## 🤖 CodeGuard AI Review

{review_result}

---
*Generated by [CodeGuard AI]({CODEGUARD_REPOSITORY_URL})*"""


def format_bug_issue(analysis, error: dict) -> str:
    """
    Format BugAnalysis (dari schemas.py, sudah tervalidasi) jadi body
    GitHub Issue. Dipakai worker.py saat fix_bug() berhasil.
    """
    lines = [
        "## 🤖 CodeGuard AI — Bug Analysis",
        "",
        f"**Error type**: `{error.get('type', 'Unknown')}`",
        f"**Message**: {error.get('message', '')}",
        "",
        "### Root Cause",
        analysis.root_cause,
        "",
        "### Affected File",
        f"`{analysis.affected_file}`" + (f" (line {analysis.affected_line})" if analysis.affected_line else ""),
        "",
        "### Fix Steps",
        analysis.fix_steps,
        "",
        "### Quick Fix",
        f"```\n{analysis.quick_fix_code}\n```",
        "",
        "### Prevention",
        analysis.prevention,
    ]

    if analysis.inferences:
        lines.append("")
        lines.append("### Inferences")
        for inf in analysis.inferences:
            lines.append(f"- **{inf.claim}** _(confidence: {inf.confidence})_ — {inf.basis}")

    if analysis.status == "PARTIAL":
        lines.append("")
        lines.append("_⚠️ Analysis dikategorikan PARTIAL oleh AI — kemungkinan ada gap informasi._")

    lines.append("")
    lines.append("---")
    lines.append(f"*Generated by [CodeGuard AI]({CODEGUARD_REPOSITORY_URL})*")

    return "\n".join(lines)


def format_bug_fallback_issue(error: dict) -> str:
    """
    Body Issue minimal kalau fix_bug() return None (semua provider gagal).
    Dipakai worker.py sebagai fallback Level 1 tanpa AI analysis.
    """
    return f"""## 🤖 CodeGuard AI — Bug Detected (analysis unavailable)

**AI analysis gagal untuk error ini** — semua provider gagal merespons dengan format valid. Berikut raw error data dari Sentry:

- **Type**: {error.get('type', 'Unknown')}
- **Message**: {error.get('message', '')}
- **File**: {error.get('file', '')}
- **Line**: {error.get('line', '')}

Perlu review manual.

---
*Generated by [CodeGuard AI]({CODEGUARD_REPOSITORY_URL})*"""
